import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

# Font configuration
[font]
normal = { family = "ZedMono Nerd Font", style = "Regular" }
bold = { family = "ZedMono Nerd Font", style = "Bold" }
italic = {family = "ZedMono Nerd Font", style = "Regular" }
size = 12

[env]
TERM = "xterm-256color"

[window]
opacity = 0.999

[selection]
save_to_clipboard = true
