import = ["~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"]

# Font configuration
[font]
normal = { family = "ZedMono Nerd Font", style = "Regular" }
bold = { family = "ZedMono Nerd Font", style = "Bold" }
italic = { family = "ZedMono Nerd Font", style = "Italic" }
bold_italic = { family = "ZedMono Nerd Font", style = "Bold Italic" }
size = 12.5

[env]
TERM = "xterm-256color"

[window]
opacity = 0.999

[selection]
save_to_clipboard = true
